---
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
ci:
  skip: [hadolint]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        entry: detect-aws-credentials --allow-missing-credentials
      - id: destroyed-symlinks
      - id: forbid-submodules
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '3.0.0'
    hooks:
      - id: shellcheck
        exclude: ^tests/.*$
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
        exclude: ^tests/.*$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
        exclude: ^(tests|.github)/.*$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
